elapsed time
WFP-Doobelepers/modmail pull request #4
Opened 2022-04-16 16:50 UTC by iikel1

2022-04-18 20:30 UTC, sabihoshi requested changes

2022-04-18 20:30 UTC, sabihoshi commented on core/thread.py
> +        embed.add_field(name="The time elapsed since the ticket was opened", value=f'<t:{int(time.time())}:R>', inline=True)
Maybe use a shorter name like "Time elapsed"

2022-04-18 22:01 UTC, iikel1 commented on core/thread.py
> +        embed.add_field(name="The time elapsed since the ticket was opened", value=f'<t:{int(time.time())}:R>', inline=True)
Okay

2022-04-20 22:40 UTC, sabihoshi approved these changes

2022-04-20 22:40 UTC, merged